- name: Simple playbook to install the Azure CLI
  hosts: localhost
  connection: local
  become: yes
  tasks:
  
    - name: Get packages needed for the install process
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - aptitude
          - curl
          - apt-transport-https
          - lsb-release
          - gnupg
          
    - name: Import the Microsoft signing key into apt
      ansible.builtin.apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present
        
    - name: Add the Azure CLI software repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_distribution_release}} main"
        filename: azure-cli
        state: present
        
    - name: Update the apt cache and install the Azure CLI
      ansible.builtin.apt:
        name: azure-cli
        update_cache: yes

