---
- name: Exploring the template module and jinja expressions
  hosts: windows
  connection: winrm
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used to build templates
  vars_files:
    - vars/planetexpress.yml


  tasks:
    - name: Configure spaceship registration
      ansible.windows.win_template: 
        src: templates/ship.cfg.j2    # name of the template on ansible controller
        dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\ship.cfg"              # name of the completed file to be placed on the target system

    - name: Configure mission orders
      ansible.windows.win_template:
        src: templates/mission-orders.txt.j2    # name of the template on ansible controller
        dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\mission-orders.txt"              # name of the completed file to be placed on the target system

